version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: tinysteps-postgres
    environment:
      POSTGRES_DB: tinystepsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tinysteps@nexorian.1
    ports:
      - "5432:5432"
    networks:
      - tinysteps-network
    volumes:
      - pgdata:/var/lib/postgresql/data 

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tinysteps-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tinystepsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tinysteps@nexorian.1
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    depends_on:
      - postgres
    networks:
      - tinysteps-network
    volumes:
      - .:/app                    # mount source for hot reload
      - ~/.m2:/root/.m2           # cache Maven dependencies
    command: ./mvnw spring-boot:run -Dspring-boot.run.fork=false

networks:
  tinysteps-network:
    driver: bridge

volumes:
  pgdata:
