version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tinysteps-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-steep-dream-a88dbjow-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_gVabIey6cqQ1
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    networks:
      - tinysteps-network
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: ./mvnw spring-boot:run -Dspring-boot.run.fork=false

networks:
  tinysteps-network:
    driver: bridge
